FROM docker.io/opensuse/tumbleweed:latest

RUN zypper in -y terraform butane git
# COPY requirements.txt /tmp/requirements.txt
# COPY requirements.yml /tmp/requirements.yml

# RUN zypper in -y python311 pkgconf-pkg-config libvirt-devel gcc python311-devel
# RUN python3 -m venv /ansible

# RUN source /ansible/bin/activate && \
#     pip install -r /tmp/requirements.txt && \
#     ansible-galaxy collection install -r /tmp/requirements.yml

# RUN dnf -y update && dnf -y install \
#     git \
#     python3-pip \
#     openssl \
#     httpd-tools \
#     && dnf clean all

# RUN ansible-galaxy collection install -r /tmp/requirements.yml
